blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogDeleteView, BlogDetailView,
                        BlogListView, BlogUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="create"),
    path("", BlogListView.as_view(), name="list"),
    path("update/<slug:slug>", BlogUpdateView.as_view(), name="update"),
    path("view/<slug:slug>", BlogDetailView.as_view(), name="view"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("", include(("main.urls", "main"), namespace="main")),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    """Создания модели записи"""

    title = models.CharField(
        max_length=150, verbose_name="Заголовок", help_text="Введите название"
    )
    content = models.TextField(
        verbose_name="Содержимое", **NULLABLE, help_text="Добавьте содержимое"
    )
    preview = models.ImageField(
        upload_to="blog_foto",
        verbose_name="Изображение",
        **NULLABLE,
        help_text="Добавьте изображение"
    )
    date_published = models.DateField(auto_now_add=True, verbose_name="Дата публикации")
    view_counter = models.PositiveIntegerField(
        verbose_name="Количество просмотров", default=0
    )
    slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"
        ordering = (
            "title",
            "date_published",
            "view_counter",
        )

    def __str__(self):
        return self.title

blog/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from pytils.translit import slugify

from blog.models import Blog
from blog.services import get_blogs_from_cache


class BlogCreateView(CreateView):
    """Для создания новой публикации"""

    model = Blog
    fields = ("title", "content", "preview", "view_counter")
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    """Просмотр всех публикаций."""

    model = Blog

    def get_queryset(self):
        queryset = get_blogs_from_cache()
        return queryset


class BlogDetailView(DetailView):
    """Просмотра детальной информации публикации."""

    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    """Редактирования публикации"""

    model = Blog
    fields = ("title", "content", "preview", "view_counter")

    def get_success_url(self):
        return reverse("blog:view", args=[self.kwargs.get("slug")])


class BlogDeleteView(DeleteView):
    """Удаления публикации"""

    model = Blog
    success_url = reverse_lazy("blog:list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-body">
                  <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <p>Удалить Публикацию "{{ object.title }}?"</p>
                      <button type="submit" class="btn btn-primary">Подтвердить</button>
                      <a href="{% url 'blog:list' %}" class="btn btn-success">Отменить</a>
                  </form>
              </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="/media/{{ object.preview }}" alt="Product Image" class="Image fluid">
                    <div class="card-body">
                        <small class="text-body-secondary">{{ object.date_of_creation }}</small>
<!--                        <p class="card-text">{{ object }} / {{ object.slug }}</p>-->
                        <h4>{{ object }}</h4>
                        <p class="card-text">{{ object.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'blog:list' %}" class="text-black">На Публикации</a></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'blog:update' object.slug %}" class="text-black">Редактировать</a></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'blog:delete' object.slug %}" class="text-black">Удалить</a></button>
                            </div>
                            <small class="text-body-secondary">Просмотров: {{ object.view_counter }} </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <button type="submit" class="btn btn-primary">
                          {% if object %}
                            Сохранить
                          {% else %}
                            Создать
                          {% endif %}
                      </button>
                  </form>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Публикации</h1>
    <h2 class="display-6">Сервиса рассылок</h2>
    <a class="btn btn btn-outline-primary mt-4" href="{% url 'blog:create' %}" role="button">Добавить Публикацию</a>
</div>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <img src="/media/{{ object.preview }}" alt="Product Image" class="Image fluid">
                <div class="card-body">
                    <h4>{{ object }}</h4>
                    <div class="d-flex justify-content-between align-items-center">
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                href="{% url 'blog:view' object.slug %}" class="text-black">Подробнее</a></button>
                        <small class="text-body-secondary"> {{ object.date_published }} </small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}