blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogDeleteView, BlogDetailView,
                        BlogListView, BlogUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="create"),
    path("", BlogListView.as_view(), name="list"),
    path("update/<slug:slug>", BlogUpdateView.as_view(), name="update"),
    path("view/<slug:slug>", BlogDetailView.as_view(), name="view"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("", include(("main.urls", "main"), namespace="main")),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import UserRegisterView, UserUpdateView, confirm_email

from . import views

app_name = UsersConfig.name


urlpatterns = [
    path("registration/", UserRegisterView.as_view(), name="registration"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("confirm-register/<str:token>/", confirm_email, name="confirm_email"),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path(
        "password-change/", views.UserPasswordChange.as_view(), name="password-change"
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password-change-done",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    """Модель для Пользователя"""

    username = None

    avatar = models.ImageField(
        upload_to="users_avatar",
        verbose_name="Аватар пользователя",
        help_text="Загрузите изображение",
        **NULLABLE
    )
    phone_number = PhoneNumberField(
        verbose_name="Номер телефона",
        help_text="Укажите номер телефона",
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=100, verbose_name="Страна", help_text="Cтрана проживания", **NULLABLE
    )
    email = models.EmailField(
        max_length=100,
        verbose_name="email",
        unique=True,
        help_text="Введите emaıl",
    )
    token = models.CharField(
        max_length=50,
        verbose_name="Токен",
        blank=True,
        null=True,
    )

    # Выбираем полем для авторизации email
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользоаптель"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("set_is_active", "Может блокировать пользователя"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    PasswordChangeForm,
    UserChangeForm,
    UserCreationForm,
)

from main.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Создания нового объекта модели User"""

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserForm(StyleFormMixin, UserChangeForm):
    """Редактирования профиля Пользователя"""

    class Meta:
        model = User
        fields = [
            "email",
            "password",
            "first_name",
            "last_name",
            "avatar",
            "phone_number",
            "country",
        ]

    def __init__(self, *args, **kwargs):
        """Сокрытия поля password"""
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()


class UserPasswordChangeForm(PasswordChangeForm):
    """Для формы смены пароля"""

    old_password = forms.CharField(
        label="Старый пароль", widget=forms.PasswordInput(attrs={"class": "form_input"})
    )
    new_password1 = forms.CharField(
        label="Новый пароль", widget=forms.PasswordInput(attrs={"class": "form_input"})
    )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={"class": "form_input"}),
    )

users/views.py
import secrets
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserForm, UserPasswordChangeForm, UserRegisterForm
from users.models import User


class UserRegisterView(CreateView):
    """Класс для создания нового Пользователя"""

    model = User
    form_class = UserRegisterForm

    def get_success_url(self):
        """Метод для определения пути, после создания Пользователя"""
        return reverse("users:login")

    def form_valid(self, form):
        """Метод верифекации email"""
        token = secrets.token_hex(16)
        user = form.save()
        user.token = token
        user.is_active = False
        user.save()
        host = self.request.get_host()
        link = f"http://{host}/users/confirm-register/{token}"
        message = f"Вы успешно зарегистрировались на сайте 'Здоровье в ложке'. Предлагаем Вам подтвердить почту {link}"
        send_mail("Верификация почты", message, settings.EMAIL_HOST_USER, [user.email])
        return super().form_valid(form)


def confirm_email(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserUpdateView(UpdateView):
    """Редактирования профиля Пользователя"""

    model = User
    success_url = reverse_lazy("users:profile")
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):

    form_class = UserPasswordChangeForm
    template_name = "users/password_change_form.html"
    success_url = reverse_lazy("users:password-change-done")

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
        <form class="row mt-4 mb-4" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                          Вход в Личный кабинет
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                         Войти
                        </button>
                        <a href="{% url 'users:password_reset' %}" class="btn btn-danger">Восстановить пароль</a>
                    </div>
                    <div class="card-footer">
                        Вам необходимо подтвердить Вашу электронную почту.
                        Пройдите по ссылке в письме.
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>Пароль успешно изменен!</h1>
 
<p >Успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>Изменение пароля</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Изменить пароль</button></p>
</form>
 
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p >Успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>Новый пароль</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>
 
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>
<p >{% translate 'Мы отправили вам по электронной почте инструкции по установке пароля, если существует учетная запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время.' %}</p>
<p >{% translate 'Если вы не получили электронное письмо, убедитесь, что вы ввели адрес, под которым зарегистрировались, и проверьте папку со спамом..' %}</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}Вы получили это электронное письмо, поскольку запросили сброс пароля для своей учетной записи на сайте {{ site_name }}.{% endblocktranslate %}

{% translate "Пожалуйста, перейдите на следующую страницу и выберите новый пароль.:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Ваше имя пользователя, если вы забыли:' %} {{ user.get_username }}

{% translate "Спасибо за использование нашего сайта!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Сбросить по E-mail</button>
    </p>
</form>
 
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <form class="row mt-4 mb-4" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {% if object %}
                        Профиль Пользователя
                        {% else %}
                        Форма регистрации на сайте
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Зарегистрировать
                        {% endif %}
                    </button>
                    {% if object %}
                    <p><a href="{% url 'users:password-change' %}" class="btn mt-4 btn-danger">Сменить пароль</a></p>
                    {% endif %}
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}