blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogDeleteView, BlogDetailView,
                        BlogListView, BlogUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="create"),
    path("", BlogListView.as_view(), name="list"),
    path("update/<slug:slug>", BlogUpdateView.as_view(), name="update"),
    path("view/<slug:slug>", BlogDetailView.as_view(), name="view"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("", include(("main.urls", "main"), namespace="main")),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import (ClientCreateView, ClientDeleteView, ClientDetailView,
                        ClientListView, ClientUpdateView, IndexView,
                        LogListView, MessageCreateView, MessageDeleteView,
                        MessageDetailView, MessageListView, MessageUpdateView,
                        NewsletterCreateView, NewsletterDeleteView,
                        NewsletterDetailView, NewsletterListView,
                        NewsletterUpdateView, toggle_activity)

app_name = MainConfig.name

urlpatterns = [
    # Путь для отображения главной страницы
    path("", cache_page(60)(IndexView.as_view()), name="index"),
    # Путь для вывода листа со всеми рассылками
    path("newsletters/", NewsletterListView.as_view(), name="newsletter_list"),
    # Путь для вывода листа с одной рассылкой
    path(
        "newsletters/<int:pk>/",
        NewsletterDetailView.as_view(),
        name="newsletter_detail",
    ),
    # Путь для создания нового объекта модели Newsletter
    path(
        "newsletters/create/", NewsletterCreateView.as_view(), name="newsletter_create"
    ),
    # Путь для редактирования рассылки
    path(
        "newsletters/<int:pk>/update/",
        NewsletterUpdateView.as_view(),
        name="newsletter_update",
    ),
    # Путь для удаления рассылки
    path(
        "newsletters/<int:pk>/delete/",
        NewsletterDeleteView.as_view(),
        name="newsletter_delete",
    ),
    # Путь для вывода листа со всеми cсообщениями
    path("messages/", MessageListView.as_view(), name="message_list"),
    # Путь для вывода листа с одном сообщением
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    # Путь для создания нового объекта модели Message
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    # Путь для редактирования сообщения
    path(
        "messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    # Путь для удаления сообщения
    path(
        "messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    # Путь для вывода листа со всеми Клиентами
    path("clients/", ClientListView.as_view(), name="client_list"),
    # Путь для вывода листа с одном Клиентом
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    # Путь для создания нового объекта модели Client
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    # Путь для редактирования Клиента
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    # Путь для удаления Клиента
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    # Путь для вывода листа с Логами
    path("logs/", LogListView.as_view(), name="logs_list"),

    path("activity/<int:pk>/", toggle_activity, name="toggle_activity"),
]

main/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Client(models.Model):
    """Класс для создание модели клиента"""

    email = models.EmailField(
        verbose_name="email", help_text="Введите Вашу электронную почту"
    )
    name = models.CharField(
        max_length=200, verbose_name="ФИО", help_text="Введите Ваши ФИО"
    )
    comment = models.TextField(
        verbose_name="Комментарий",
        blank=True,
        null=True,
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        related_name="clients",
        on_delete=models.CASCADE,
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    def __str__(self):
        return f"Клиент сервиса: {self.name}"


class Message(models.Model):
    """Класс для создания модели Сообщения рассылки"""

    subject = models.CharField(
        max_length=200, verbose_name="тема письма", help_text="Укажите тему сообщения"
    )
    body = models.TextField(
        verbose_name="Тело письма", help_text="Заполните тело сообщения"
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        on_delete=models.CASCADE,
        related_name="messages",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        permissions = [
            ("set_update", "Может менять сообщения"),
        ]

    def __str__(self):
        return f"Тема: {self.subject}. содержание: {self.body}"


class Newsletter(models.Model):
    """Класс для создания модели Рассылки"""

    CHOICES_PERIOD = [
        ("daily", "раз в день"),
        ("weekly", "раз в неделю"),
        ("monthly", "раз в месяц"),
    ]

    STATUS_CHOICES = [
        ("completed", "Завершена"),
        ("created", "Создана"),
        ("launched", "Запущена"),
    ]

    title = models.CharField(
        max_length=200,
        verbose_name=" Название рассылки",
        help_text="Напишите название рассылки",
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор рассылки",
        related_name="newsletters",
        on_delete=models.CASCADE,
        **NULLABLE,
    )
    message = models.ForeignKey(
        Message, verbose_name="Сообщение рассылки", on_delete=models.CASCADE
    )
    datetime_start = models.DateTimeField(
        default=timezone.now, verbose_name="Дата начала рассылки"
    )
    datetime_send = models.DateTimeField(
        default=timezone.now, verbose_name="Дата отправки"
    )
    datetime_finish = models.DateTimeField(
        default=timezone.now, verbose_name="Дата окончания рассылки"
    )
    periodicity = models.CharField(
        max_length=50, choices=CHOICES_PERIOD, verbose_name="Периодичность"
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default="created",
        verbose_name="Статус рассылки",
    )
    clients = models.ManyToManyField(Client, verbose_name="Получатели рассылки")
    is_active = models.BooleanField(default=True, verbose_name="Актуальность")

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [
            ("set_is_active", "Может менять активность рассылки"),
        ]

    def __str__(self):
        return f"Рассылка {self.title}"


class Log(models.Model):
    """Класс для создания модели Сообщения"""

    newsletter = models.ForeignKey(
        Newsletter,
        verbose_name="Рассылка",
        on_delete=models.CASCADE,
        related_name="logs",
    )
    last_time_send = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время последней попытки"
    )
    status = models.CharField(max_length=50, verbose_name="Статус попытки")
    server_response = models.TextField(verbose_name="Ответ сервера", **NULLABLE)

    owner = models.ForeignKey(User, verbose_name="Владелец Логов", on_delete=models.CASCADE, **NULLABLE)

    class Meta:
        verbose_name = "Лог"
        verbose_name_plural = "Логи"

    def __str__(self):
        return f"{self.newsletter}. Дата и время последней попытки:{self.last_time_send}, статус попытки:{self.status}"

main/forms.py
from django.forms import BooleanField, DateTimeInput, ModelForm

from main.models import Client, Message, Newsletter


# Данный класс создаем для стилизации форм, Это Mixin, класс ни от чего не наследуется
class StyleFormMixin:
    """Класс для стилизации форм"""

    # Переопределяем метод __init__
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Так как мы получаем словарь, для выведения обоих значение (value| key) применяем значение items()
        for field_name, field in self.fields.items():
            # Задаем условия - если у поля Булевое значение
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class NewsletterForm(StyleFormMixin, ModelForm):
    """Класс создания форм для модели Newsletter"""

    class Meta:
        model = Newsletter
        exclude = ("datetime_send", "author")

        widgets = {
            "datetime_start": DateTimeInput(
                attrs={"placeholder": "ДД.ММ.ГГГГ ЧЧ:ММ:СС", "type": "datetime-local"}
            ),
            "datetime_finish": DateTimeInput(
                attrs={"placeholder": "ДД.ММ.ГГГГ ЧЧ:ММ:СС", "type": "datetime-local"}
            ),
        }


class MessageForm(StyleFormMixin, ModelForm):
    """Класс создания форм для модели Message"""

    class Meta:
        model = Message
        fields = ("subject", "body")


class ClientForm(StyleFormMixin, ModelForm):
    """Класс создания форм для модели Client"""

    class Meta:
        model = Client
        fields = ("email", "name")

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from blog.models import Blog
from main.forms import ClientForm, MessageForm, NewsletterForm
from main.models import Client, Log, Message, Newsletter


class NewsletterListView(ListView):
    """Класс для отображения всех рассылок"""

    model = Newsletter


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    """Класс для вывода страницы с одной рассылкой по pk"""

    model = Newsletter


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания новой рассылки"""

    model = Newsletter
    form_class = NewsletterForm

    success_url = reverse_lazy("main:newsletter_list")

    def form_valid(self, form):
        """Метод для автоматического привязывания Пользователя к создаваемой Рассылке"""
        # Сохранение формы
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()

        return super().form_valid(form)


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    """Класс для редактирования рассылки"""

    model = Newsletter
    form_class = NewsletterForm

    def get_success_url(self):
        """Метод для определения пути, куда будет совершен переход после редактирования рассылки"""
        return reverse("main:newsletter_detail", args=[self.get_object().pk])

    def get_form_class(self):
        """
        Метод, который позволяет вывести Пользователю правильную форму для редактирования,
        в зависимости от прав доступа Пользователя.
        """
        user = self.request.user
        if user == self.object.author or self.request.user.is_superuser:
            return NewsletterForm

        raise PermissionDenied


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    """Класс для удаления рассылки"""

    model = Newsletter
    success_url = reverse_lazy("main:newsletter_list")


class MessageListView(ListView):
    """Класс для отображения всех созданных сообщений"""

    model = Message


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Класс для вывода страницы с одним сообщением по pk"""

    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания нового сообщения"""

    model = Message
    form_class = MessageForm

    success_url = reverse_lazy("main:message_list")

    def form_valid(self, form):
        """
        Метод для автоматического привязывания Пользователя к создаваемому Сообщению
        """
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Класс для редактирования сообщения"""

    model = Message
    form_class = MessageForm

    def get_success_url(self):
        """Метод для определения пути, куда будет совершен переход после редактирования сообщения"""
        return reverse("main:message_detail", args=[self.get_object().pk])


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Класс для удаления сообщения"""

    model = Message
    success_url = reverse_lazy("main:message_list")


class ClientListView(ListView):
    """Класс для отображения всех созданных Клиентов"""

    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    """Класс для вывода страницы с одним Клиентом по pk"""

    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания нового Клиент"""

    model = Client
    form_class = ClientForm

    success_url = reverse_lazy("main:client_list")

    def form_valid(self, form):
        """
        Метод для автоматического привязывания Пользователя к создаваемому Клиенту
        """
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Класс для редактирования Клиента"""

    model = Client
    form_class = ClientForm

    def get_success_url(self):
        """Метод для определения пути, куда будет совершен переход после редактирования сообщения"""
        return reverse("main:client_detail", args=[self.get_object().pk])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """Класс для удаления Клиента"""

    model = Client
    success_url = reverse_lazy("main:client_list")


class IndexView(TemplateView):
    """
    Класс для отображения главной страницы с показателями статистики по сайту.
    """

    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        """
        Метод получения данных для отображения в виде статистики на Главной странице Проекта.
        """
        context = super().get_context_data(**kwargs)
        article_list = Blog.objects.all()[:3]
        context["article_list"] = article_list
        newsletter_count = Newsletter.objects.all().count()
        context["newsletter_count"] = newsletter_count

        unique_clients_count = Client.objects.all().values("email").distinct().count()
        context["unique_clients_count"] = unique_clients_count

        active_newsletter_count = Newsletter.objects.filter(is_active=True).count()
        context["active_newsletter_count"] = active_newsletter_count
        return context


class LogListView(ListView):
    """
    Класс для отображения всех созданных Логов.
    """

    model = Log

    def get_queryset(self, *args, **kwargs):
        """
        Метод для вывода листа с Логами только для Автора рассылок, при отправке которых эти Логи сформированы.
        """
        user = self.request.user
        if user.is_staff or user.is_superuser:
            queryset = super().get_queryset(*args, **kwargs)
        else:
            queryset = super().get_queryset().filter(owner=user)
        return queryset


def toggle_activity(request, pk):
    """
    Функция для Модератора по смене активности рассылки.
    """
    newsletter_status = get_object_or_404(Newsletter, pk=pk)
    if newsletter_status.is_active is True:
        newsletter_status.is_active = False

    elif newsletter_status.is_active is False:
        newsletter_status.is_active = True

    newsletter_status.save()
    return redirect(reverse("main:newsletter_list"))

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-body">
                  <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <p>Удалить Клиента "{{ object.mail }}?"</p>
                      <button type="submit" class="btn btn-primary">Подтвердить</button>
                      <a href="{% url 'main:client_list' %}" class="btn btn-success">Отменить</a>
                  </form>
              </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ client }}</p>
                        <p class="card-text">email Клиента: {{ client.email }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:client_list' %}" class="text-black">На список клиентов</a></button>
                            <small class="text-body-secondary">Автор: {{ object.owner }} </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            {% if object %}
                            Редактирование Клиента
                             {% else %}
                            Создание нового Клиента
                            {% endif %}
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Сервис рассылок</h1>
        <h2 class="fw-light">Раздел "Клиенты"</h2>
        <p class="lead text-body-secondary">Сервис рассылок</p>
        <a class="btn btn btn-outline-primary mt-4" href="{% url 'main:client_create' %}" role="button">Добавить Клиента</a>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for client in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ client }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if user == message.owner %}
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:client_detail' client.pk %}" class="text-black">Подробнее</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:client_update' client.pk %}" class="text-black">Редактирование</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:client_delete' client.pk %}" class="text-black">Удалить</a></button>
                  {% endif %}
                </div>
                <small class="text-body-secondary px-3">Автор: {{ client.owner }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            {% if object %}
                            Редактирование Клиента
                             {% else %}
                            Создание нового Клиента
                            {% endif %}
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/log_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Сервис рассылок</h1>
        <h2 class="fw-light">Раздел "Сообщения"</h2>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for log in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ log }}</p>
              <div class="d-flex justify-content-between align-items-center">
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Сервис рассылок</h1>
        <h2 class="fw-light">Раздел "Сообщения"</h2>
        <a class="btn btn btn-outline-primary mt-4" href="{% url 'main:message_create' %}" role="button">Добавить Сообщение</a>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for message in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ message }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:message_detail' message.pk %}" class="text-black">Подробнее</a></button>
                  {% if user == message.author %}
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:message_update' message.pk %}" class="text-black">Редактирование</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:message_delete' message.pk %}" class="text-black">Удалить</a></button>
                  {% endif %}
                </div>
                <small class="text-body-secondary px-3">Автор: {{ message.author }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/newsletter_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Сервис рассылок</h1>
        <h2 class="fw-light">Раздел "Рассылки"</h2>
        <a class="btn btn btn-outline-primary mt-4" href="{% url 'main:newsletter_create' %}" role="button">Добавить Рассылку</a>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for newsletter in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ newsletter }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:newsletter_detail' newsletter.pk %}" class="text-black">Подробнее</a></button>
                  {% if user == newsletter.author %}
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:newsletter_update' newsletter.pk %}" class="text-black">Редактирование</a></button>
                  {% endif %}

                  {% if user == newsletter.author %}
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'main:newsletter_delete' newsletter.pk %}" class="text-black">Удалить</a></button>
                  {% endif %}
                </div>
                <small class="text-body-secondary px-3">Автор: {{ newsletter.author }}</small>
              </div>
                  {% if user.is_authenticated %}
                  {% if perms.main.set_is_active %}
                  {% if newsletter.is_active %}
                  <a href="{% url 'main:toggle_activity' newsletter.pk %}" class="double-border-button">Деактивировать</a>
                  {% else%}
                  <a href="{% url 'main:toggle_activity' newsletter.pk %}" class="double-border-button">Активировать</a>
                  {% endif %}
                  {% endif %}
                  {% endif %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}